---
resources:
- name: this-git-repo
  type: git
  source:
    uri: https://github.com/martyca/concourse-tests.git

jobs:
- name: job-deploy-webapp
  serial: true
  plan:
  - get: this-git-repo
    trigger: true
  - task: blue-green
    file: this-git-repo/jobs/blue-green.yml
    params:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}
