---
resources:
- name: this-git-repo
  type: git
  source:
    uri: https://github.com/martyca/concourse-tests.git

- name: resource-deploy-webapp
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
jobs:
- name: job-hello-world
  public: true
  plan:
  - get: this-git-repo
  - task: hello-world
    file: this-git-repo/jobs/hello-world.yml
- name: job-deploy-webapp
  public: true
  plan:
  - get: this-git-repo
    trigger: true
  - put: resource-deploy-webapp
    params:
      manifest: this-git-repo/webapp/deploy-webapp.manifest
      path: this-git-repo/webapp
